# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lostOrFound', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=750)),
                ('date', models.DateField()),
            ],
        ),
    ]
