# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='lostOrFound',
            new_name='status',
        ),
    ]
