# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171203_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
