# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_item_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
